/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenresAnimeRouteImport } from './routes/genres/anime'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime/$animeId'
import { Route as AnimeAnimeIdThemesRouteImport } from './routes/anime/$animeId/themes'
import { Route as AnimeAnimeIdStreamingRouteImport } from './routes/anime/$animeId/streaming'
import { Route as AnimeAnimeIdPicturesRouteImport } from './routes/anime/$animeId/pictures'
import { Route as AnimeAnimeIdEpisodesRouteImport } from './routes/anime/$animeId/episodes'
import { Route as AnimeAnimeIdCharactersRouteImport } from './routes/anime/$animeId/characters'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresAnimeRoute = GenresAnimeRouteImport.update({
  id: '/genres/anime',
  path: '/genres/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdThemesRoute = AnimeAnimeIdThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdStreamingRoute = AnimeAnimeIdStreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdPicturesRoute = AnimeAnimeIdPicturesRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdEpisodesRoute = AnimeAnimeIdEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdCharactersRoute = AnimeAnimeIdCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/genres/anime': typeof GenresAnimeRoute
  '/anime/$animeId/characters': typeof AnimeAnimeIdCharactersRoute
  '/anime/$animeId/episodes': typeof AnimeAnimeIdEpisodesRoute
  '/anime/$animeId/pictures': typeof AnimeAnimeIdPicturesRoute
  '/anime/$animeId/streaming': typeof AnimeAnimeIdStreamingRoute
  '/anime/$animeId/themes': typeof AnimeAnimeIdThemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/genres/anime': typeof GenresAnimeRoute
  '/anime/$animeId/characters': typeof AnimeAnimeIdCharactersRoute
  '/anime/$animeId/episodes': typeof AnimeAnimeIdEpisodesRoute
  '/anime/$animeId/pictures': typeof AnimeAnimeIdPicturesRoute
  '/anime/$animeId/streaming': typeof AnimeAnimeIdStreamingRoute
  '/anime/$animeId/themes': typeof AnimeAnimeIdThemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/genres/anime': typeof GenresAnimeRoute
  '/anime/$animeId/characters': typeof AnimeAnimeIdCharactersRoute
  '/anime/$animeId/episodes': typeof AnimeAnimeIdEpisodesRoute
  '/anime/$animeId/pictures': typeof AnimeAnimeIdPicturesRoute
  '/anime/$animeId/streaming': typeof AnimeAnimeIdStreamingRoute
  '/anime/$animeId/themes': typeof AnimeAnimeIdThemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/anime/$animeId'
    | '/genres/anime'
    | '/anime/$animeId/characters'
    | '/anime/$animeId/episodes'
    | '/anime/$animeId/pictures'
    | '/anime/$animeId/streaming'
    | '/anime/$animeId/themes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/anime/$animeId'
    | '/genres/anime'
    | '/anime/$animeId/characters'
    | '/anime/$animeId/episodes'
    | '/anime/$animeId/pictures'
    | '/anime/$animeId/streaming'
    | '/anime/$animeId/themes'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/anime/$animeId'
    | '/genres/anime'
    | '/anime/$animeId/characters'
    | '/anime/$animeId/episodes'
    | '/anime/$animeId/pictures'
    | '/anime/$animeId/streaming'
    | '/anime/$animeId/themes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRouteWithChildren
  GenresAnimeRoute: typeof GenresAnimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/anime': {
      id: '/genres/anime'
      path: '/genres/anime'
      fullPath: '/genres/anime'
      preLoaderRoute: typeof GenresAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId/themes': {
      id: '/anime/$animeId/themes'
      path: '/themes'
      fullPath: '/anime/$animeId/themes'
      preLoaderRoute: typeof AnimeAnimeIdThemesRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/streaming': {
      id: '/anime/$animeId/streaming'
      path: '/streaming'
      fullPath: '/anime/$animeId/streaming'
      preLoaderRoute: typeof AnimeAnimeIdStreamingRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/pictures': {
      id: '/anime/$animeId/pictures'
      path: '/pictures'
      fullPath: '/anime/$animeId/pictures'
      preLoaderRoute: typeof AnimeAnimeIdPicturesRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/episodes': {
      id: '/anime/$animeId/episodes'
      path: '/episodes'
      fullPath: '/anime/$animeId/episodes'
      preLoaderRoute: typeof AnimeAnimeIdEpisodesRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/characters': {
      id: '/anime/$animeId/characters'
      path: '/characters'
      fullPath: '/anime/$animeId/characters'
      preLoaderRoute: typeof AnimeAnimeIdCharactersRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
  }
}

interface AnimeAnimeIdRouteChildren {
  AnimeAnimeIdCharactersRoute: typeof AnimeAnimeIdCharactersRoute
  AnimeAnimeIdEpisodesRoute: typeof AnimeAnimeIdEpisodesRoute
  AnimeAnimeIdPicturesRoute: typeof AnimeAnimeIdPicturesRoute
  AnimeAnimeIdStreamingRoute: typeof AnimeAnimeIdStreamingRoute
  AnimeAnimeIdThemesRoute: typeof AnimeAnimeIdThemesRoute
}

const AnimeAnimeIdRouteChildren: AnimeAnimeIdRouteChildren = {
  AnimeAnimeIdCharactersRoute: AnimeAnimeIdCharactersRoute,
  AnimeAnimeIdEpisodesRoute: AnimeAnimeIdEpisodesRoute,
  AnimeAnimeIdPicturesRoute: AnimeAnimeIdPicturesRoute,
  AnimeAnimeIdStreamingRoute: AnimeAnimeIdStreamingRoute,
  AnimeAnimeIdThemesRoute: AnimeAnimeIdThemesRoute,
}

const AnimeAnimeIdRouteWithChildren = AnimeAnimeIdRoute._addFileChildren(
  AnimeAnimeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRouteWithChildren,
  GenresAnimeRoute: GenresAnimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
