/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TopAnimeRouteImport } from './routes/top-anime'
import { Route as SeasonalRouteImport } from './routes/seasonal'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime/$animeId'
import { Route as AnimeAnimeIdThemesRouteImport } from './routes/anime/$animeId/themes'
import { Route as AnimeAnimeIdStreamingRouteImport } from './routes/anime/$animeId/streaming'
import { Route as AnimeAnimeIdPicturesRouteImport } from './routes/anime/$animeId/pictures'
import { Route as AnimeAnimeIdEpisodesRouteImport } from './routes/anime/$animeId/episodes'
import { Route as AnimeAnimeIdCharactersRouteImport } from './routes/anime/$animeId/characters'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TopAnimeRoute = TopAnimeRouteImport.update({
  id: '/top-anime',
  path: '/top-anime',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonalRoute = SeasonalRouteImport.update({
  id: '/seasonal',
  path: '/seasonal',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdThemesRoute = AnimeAnimeIdThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdStreamingRoute = AnimeAnimeIdStreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdPicturesRoute = AnimeAnimeIdPicturesRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdEpisodesRoute = AnimeAnimeIdEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const AnimeAnimeIdCharactersRoute = AnimeAnimeIdCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/genres': typeof GenresRoute
  '/schedules': typeof SchedulesRoute
  '/search': typeof SearchRoute
  '/seasonal': typeof SeasonalRoute
  '/top-anime': typeof TopAnimeRoute
  '/upcoming': typeof UpcomingRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/anime/$animeId/characters': typeof AnimeAnimeIdCharactersRoute
  '/anime/$animeId/episodes': typeof AnimeAnimeIdEpisodesRoute
  '/anime/$animeId/pictures': typeof AnimeAnimeIdPicturesRoute
  '/anime/$animeId/streaming': typeof AnimeAnimeIdStreamingRoute
  '/anime/$animeId/themes': typeof AnimeAnimeIdThemesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/genres': typeof GenresRoute
  '/schedules': typeof SchedulesRoute
  '/search': typeof SearchRoute
  '/seasonal': typeof SeasonalRoute
  '/top-anime': typeof TopAnimeRoute
  '/upcoming': typeof UpcomingRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/anime/$animeId/characters': typeof AnimeAnimeIdCharactersRoute
  '/anime/$animeId/episodes': typeof AnimeAnimeIdEpisodesRoute
  '/anime/$animeId/pictures': typeof AnimeAnimeIdPicturesRoute
  '/anime/$animeId/streaming': typeof AnimeAnimeIdStreamingRoute
  '/anime/$animeId/themes': typeof AnimeAnimeIdThemesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/genres': typeof GenresRoute
  '/schedules': typeof SchedulesRoute
  '/search': typeof SearchRoute
  '/seasonal': typeof SeasonalRoute
  '/top-anime': typeof TopAnimeRoute
  '/upcoming': typeof UpcomingRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/anime/$animeId/characters': typeof AnimeAnimeIdCharactersRoute
  '/anime/$animeId/episodes': typeof AnimeAnimeIdEpisodesRoute
  '/anime/$animeId/pictures': typeof AnimeAnimeIdPicturesRoute
  '/anime/$animeId/streaming': typeof AnimeAnimeIdStreamingRoute
  '/anime/$animeId/themes': typeof AnimeAnimeIdThemesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/genres'
    | '/schedules'
    | '/search'
    | '/seasonal'
    | '/top-anime'
    | '/upcoming'
    | '/anime/$animeId'
    | '/anime/$animeId/characters'
    | '/anime/$animeId/episodes'
    | '/anime/$animeId/pictures'
    | '/anime/$animeId/streaming'
    | '/anime/$animeId/themes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/genres'
    | '/schedules'
    | '/search'
    | '/seasonal'
    | '/top-anime'
    | '/upcoming'
    | '/anime/$animeId'
    | '/anime/$animeId/characters'
    | '/anime/$animeId/episodes'
    | '/anime/$animeId/pictures'
    | '/anime/$animeId/streaming'
    | '/anime/$animeId/themes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/genres'
    | '/schedules'
    | '/search'
    | '/seasonal'
    | '/top-anime'
    | '/upcoming'
    | '/anime/$animeId'
    | '/anime/$animeId/characters'
    | '/anime/$animeId/episodes'
    | '/anime/$animeId/pictures'
    | '/anime/$animeId/streaming'
    | '/anime/$animeId/themes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GenresRoute: typeof GenresRoute
  SchedulesRoute: typeof SchedulesRoute
  SearchRoute: typeof SearchRoute
  SeasonalRoute: typeof SeasonalRoute
  TopAnimeRoute: typeof TopAnimeRoute
  UpcomingRoute: typeof UpcomingRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-anime': {
      id: '/top-anime'
      path: '/top-anime'
      fullPath: '/top-anime'
      preLoaderRoute: typeof TopAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasonal': {
      id: '/seasonal'
      path: '/seasonal'
      fullPath: '/seasonal'
      preLoaderRoute: typeof SeasonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId/themes': {
      id: '/anime/$animeId/themes'
      path: '/themes'
      fullPath: '/anime/$animeId/themes'
      preLoaderRoute: typeof AnimeAnimeIdThemesRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/streaming': {
      id: '/anime/$animeId/streaming'
      path: '/streaming'
      fullPath: '/anime/$animeId/streaming'
      preLoaderRoute: typeof AnimeAnimeIdStreamingRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/pictures': {
      id: '/anime/$animeId/pictures'
      path: '/pictures'
      fullPath: '/anime/$animeId/pictures'
      preLoaderRoute: typeof AnimeAnimeIdPicturesRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/episodes': {
      id: '/anime/$animeId/episodes'
      path: '/episodes'
      fullPath: '/anime/$animeId/episodes'
      preLoaderRoute: typeof AnimeAnimeIdEpisodesRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/anime/$animeId/characters': {
      id: '/anime/$animeId/characters'
      path: '/characters'
      fullPath: '/anime/$animeId/characters'
      preLoaderRoute: typeof AnimeAnimeIdCharactersRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
  }
}

interface AnimeAnimeIdRouteChildren {
  AnimeAnimeIdCharactersRoute: typeof AnimeAnimeIdCharactersRoute
  AnimeAnimeIdEpisodesRoute: typeof AnimeAnimeIdEpisodesRoute
  AnimeAnimeIdPicturesRoute: typeof AnimeAnimeIdPicturesRoute
  AnimeAnimeIdStreamingRoute: typeof AnimeAnimeIdStreamingRoute
  AnimeAnimeIdThemesRoute: typeof AnimeAnimeIdThemesRoute
}

const AnimeAnimeIdRouteChildren: AnimeAnimeIdRouteChildren = {
  AnimeAnimeIdCharactersRoute: AnimeAnimeIdCharactersRoute,
  AnimeAnimeIdEpisodesRoute: AnimeAnimeIdEpisodesRoute,
  AnimeAnimeIdPicturesRoute: AnimeAnimeIdPicturesRoute,
  AnimeAnimeIdStreamingRoute: AnimeAnimeIdStreamingRoute,
  AnimeAnimeIdThemesRoute: AnimeAnimeIdThemesRoute,
}

const AnimeAnimeIdRouteWithChildren = AnimeAnimeIdRoute._addFileChildren(
  AnimeAnimeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GenresRoute: GenresRoute,
  SchedulesRoute: SchedulesRoute,
  SearchRoute: SearchRoute,
  SeasonalRoute: SeasonalRoute,
  TopAnimeRoute: TopAnimeRoute,
  UpcomingRoute: UpcomingRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
